import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import React from 'react'
import File from '../components/file'
import { S3File, S3RootData } from './api/s3/root'

const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  const [rootFiles, setRootFiles] = React.useState<S3File[]>([])
  const [rootFolders, setRootFolders] = React.useState<string[]>([])
  async function loadS3RootObjects() {
    try {
      const res: S3RootData = await fetch('/api/s3/root').then(r => r.json())
      setRootFolders(res.folders)
      setRootFiles(res.files)
    } catch (e) {
      console.error(e)
      console.error('loadS3Objects failed')
    }
  }
  React.useEffect(() => {
    loadS3RootObjects()
  }, [])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="info">
          <h1>Roli Tech Test - S3 File Browser</h1>
          <p>S3 Bucket name: {process.env.NEXT_PUBLIC_S3_BUCKET_NAME}</p>
          <p>S3 Bucket region: {process.env.NEXT_PUBLIC_S3_REGION}</p>
        </div>
        <div className="s3-objects">
          <ul className="files">
            {rootFolders.map(folderName => <li key={folderName}>{folderName}</li>)}
          </ul>
          <ul className="files">
            {rootFiles.map(f => <li key={f.name}>
              <File name={f.name} url={f.url}></File>
            </li>)}
          </ul>
        </div>
      </main>
    </>
  )
}
