import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import React from 'react'
import File from '../components/file'
import { S3File, S3RootData } from './api/s3/root'

const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  const [files, setFiles] = React.useState<S3File[]>([])
  const [folders, setFolders] = React.useState<string[]>([])
  const [prefix, setPrefix] = React.useState<string>('')
  async function loadS3Objects() {
    try {
      const res: S3RootData = await fetch('/api/s3/root').then(r => r.json())
      setFolders(res.folders)
      setFiles(res.files)
    } catch (e) {
      console.error(e)
      console.error('loadS3Objects failed')
    }
  }
  React.useEffect(() => {
    loadS3Objects()
  }, [])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.titleBackground}>
          <h1 className={styles.title}>Roli Tech Test - S3 File Browser</h1>
        </div>
        <div className={styles.fileExplorer}>
          <div className={styles.sideBar}>
            <div className={styles.buttonContainer}>
              <span className={styles.buttonRed}></span>
              <span className={styles.buttonYellow}></span>
              <span className={styles.buttonGreen}></span>
            </div>
          </div>
          <div className={styles.explorerMain}>
            <div className={styles.explorerTop}>
              <code className={styles.lsCmd}>
                <span className={styles.caret}>{'>'}</span> aws s3 list-objects --region {process.env.NEXT_PUBLIC_S3_REGION} --delimiter '/' --prefix '{prefix}' s3://{process.env.NEXT_PUBLIC_S3_BUCKET_NAME}/
              </code>
            </div>
            <ul className={styles.list}>
              {folders.map(folderName => <li key={folderName}>{folderName}</li>)}
              {files.map(f => <li key={f.name}>
                <File name={f.name} url={f.url}></File>
              </li>)}
            </ul>
            <div className={styles.explorerFooter}>
              <p>{folders.length} folders, {files.length} files</p>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
